#!/usr/bin/env bash

[[ "$(whoami)" = "root" ]] && echo "Script must be run as a normal user." && exit

# Colors
RED="\033[1;31m"
GREEN="\033[1;32m"
END="\033[0m"

update() {
  echo -e "\n${GREEN}Downloading the latest version...${END}"
  wget https://tlauncher.org/jar -P /tmp
  unzip /tmp/jar -d /tmp/tlauncher
  sudo mv /tmp/tlauncher/*.jar /usr/share/tlauncher/tlauncher.jar
  rm /tmp/jar
  rm -rf /tmp/tlauncher/
  echo -e "\n${GREEN}Done!${END}"
}

usage() {
  echo "
  Usage:
    --update, update | Update tlauncher.jar
    --remove, remove | Remove tlauncher from your system, except your \$HOME/.minecraft dir 
    nothing          | Launch TLauncher
  "
}

remove() {
  SYSTEM_FILES=(
    /usr/share/tlauncher
    /usr/share/icons/tlauncher.png
    /usr/share/applications/tlauncher.desktop
    /usr/bin/tlauncher
  )
  echo -e "\n${GREEN}Removing TLauncher system files...${END}"
  rm -rf "${SYSTEM_FILES[@]}"
  echo -en "\nDo you want to keep all those java packages installed (${GREEN}Yy${END}/${RED}Nn${END})?" && read -r KEEP_JAVA
  echo -en "\nDo you want to keep your \$HOME/.tlauncher dir (${GREEN}Yy${END}/${RED}Nn${END})?" && read -r KEEP_DOTDIR
  [[ "${KEEP_JAVA,,}" = "n" ]] && sudo pacman -Rns jdk-openjdk jre-openjdk{,-headless} java-openjfx
  [[ "${KEEP_DOTDIR,,}" = "n" ]] && rm -rf "$HOME/.tlauncher"
}


case "$1" in
  -u|--update|update)
    update ; exit ;;
  -r|--remove|remove)
    remove ; exit ;;
  *)
    usage  ; exit ;;
esac


java -jar /usr/share/tlauncher/tlauncher.jar
